### PR TITLE
Mangling fixes

### PR DESCRIPTION
**Pull request by AndreyE**
Fixes for https://github.com/KhronosGroup/SPIRV-LLVM/issues/44

### CODE REVIEW

**Comment by yxsamliu** [comment]
Can you add lit tests for each change?

**Comment by AndreyE** [comment]
I will add a LIT test for the mangling compression and mangling of device execution built-ins. I've stumbled over these bugs for enqueue_kernel built-in only, so I don't know how to reproduce mangling compression issue other way.
For kernel_enqueue_flags_t and clk_profiling_info as int I'm not sure what test to add because it depends on compile time definition.

**Comment by AndreyE** [comment]
Added a LIT test. Sam, please, review.

**Comment by yxsamliu** [comment]
Merge failed due to head change. Can you resolve the conflicts and update the pull request? Thanks.

**Comment by AndreyE** [comment]
Rebased

**Pull request merged**
