### PR TITLE
[SPIRV] github issue#5 Capabilities required by OpDecorate are not ad…

### PR DESCRIPTION
**Pull request by yxsamliu**
…ded to SPIR-V.

When generating a SPIR-V binary from the sames files as in #3 (LLVM code and OpenCL kernel), noOpCapability Kernel is generated (required by OpEntryPoint Kernel, OpMemoryModel OpenCL, OpDecorate FuncParamAttr, OpDecorate Constant), nor OpCapability Linkage, which is required by OpDecorate LinkageAttributes.

Add capability when adding entry points to module.
Add required capability for decorations.
Refactor getCapability() so that empty capability can be returned.
Removed CapabilityNone.
Add name map for Capability.
Rename isValid(SPIRVId) to isValidId for clarity since SPIRVId is just typedef of uint32_t.
Reorder name maps and isValid functions in SPIRVEnum.h for further auto generation.
Add lit test for CapabilityKernel and CapabilityLinkage.

### CODE REVIEW

**Comment by pierremoreau** [comment]
I do get `OpCapabilityLinkage` and `OpCapabilityAddresses` added for the exampled linked in #5! I also get Shader, apparently required by the use of `OpDecorateBuiltin`. However, `OpCapabilityShader` itself requires `OpCapabilityMatrix`, which was not added.

**Comment by yxsamliu** [comment]
OpDecorateBuiltin should not requires CapabilityShader since Kernel also uses it. This seems to be a spec issue.

**Comment by pierremoreau** [comment]
I also found it weird… incoming patch to handle capabilities depending on another capability.

**Comment by pierremoreau** [comment]
https://gist.github.com/pierremoreau/5ebe7c4439249aaa9a35 should take care of capabilities dependencies. Could you add it to this pull request please?

Oh, and minor nitpick: the related open issue is #5, not #6 (in your commit message). :-)

**Comment by yxsamliu** [comment]
Thanks for reminding me about the commit message. I have fixed it.
I think it is better to create another pull request for your fix. I have some other changes incoming for fixing the incorrect capability Shader and Float64.

**Pull request merged**
