### PR TITLE
LLVM SPIR-V changes for SPV_INTEL_subgroups

### PR DESCRIPTION
**Pull request by AlexeySotkin**

### CODE REVIEW

**Comment by yxsamliu** [comment]
LGTM. Thanks.

**Comment by yxsamliu** [comment]
LGTM.

**Comment by oscarbg** [comment]
@AlexeySotkin some questions:
a) is this extension only supported on Intel GPU OpenCL driver or also Intel CPU OpenCL driver(say exposed using some shuffle AVX instructions)?
b) is this SPIR-V extension also supported on Intel Vulkan driver on compute shaders or plans to do so?
c) is this extension supported on any public Intel Graphics Windows OpenCL driver?
d) plans for Linux support.. either on intel-opencl-r5.0 (SRB5.0) Linux driver package (proprietary closed Intel OpenCL driver) or Intel open source Beignet once SPIR-V gets added..
e) relation to expected coming soon Khronos Vulkan shuffle extension?
thanks..

**Comment by AlexeySotkin** [comment]
@oscarbg, currently Intel GPU device supports this extension on both Windows and Linux OS. But I don't comment on future extensions and API roadmaps.

**Comment by AlexeySotkin** [comment]
@yxsamliu There are 2 "LGTM" comments from you. Can I assume that one of them is for https://github.com/KhronosGroup/SPIR/pull/75 ?

**Comment by yxsamliu** [comment]
Right. Sorry for that.

**Pull request merged**
