### PR TITLE
Spirv 1 1 support

### PR DESCRIPTION
**Pull request by ldudziak**
Implementation of mechanism responsible for auto detection of required SPIRV version (1.0 or 1.1).
Please note that currently no features from SPIRV 1.1 are supported - relevant changes (Initializer/Finalizer execution modes, MaxByteOffset and PipeStorage) are already made and will be pulled after this request.

### CODE REVIEW

**Comment by yxsamliu** [comment]
SPIRVIsValidEnum.h needs to be regenerated to match spirv.hpp.

What if the llvm module specifies SPIRV version 1.0 but uses some 1.1 features. Will there be warning or error emitted, or the translator just silently bump up the SPIRV version to 1.1?

**Comment by ldudziak** [comment]
Thanks for your comment Sam, I will regenerate SPIRVIsValidEnum.h. About SPIRV version: I'm unaware of any way llvm module could specify usage of SPIRV 1.0 (neither C nor C++ compiler produce such information), so to answer your question - currently translator will silently bump up to 1.1.

**Comment by yxsamliu** [comment]
You are right. I think I was confused about the SPIR-V version and SPIR version.

**Comment by yxsamliu** [comment]
I forgot to request for squashing the commits before merging it. Can you squash your commits and create another pull request? Thanks.

**Comment by bader** [comment]
Sam, you can squash commits during the merge.
When you confirm the merge there should be drop down list with an option to squash commits before the merge.

**Comment by yxsamliu** [comment]
Thanks Alexey. I will try that next time.

Lukasz, no need to create a new pull request. I have squashed the commits manually.

**Pull request merged**
