### PR TITLE
Setting name of target of LinkageAttributes decoration to literal val…

### PR DESCRIPTION
**Pull request by AlexeySotkin**
…ue of the decoration.

Also enabling .spt files in LIT tests

### CODE REVIEW

**Comment by bader** [comment]
LGTM. Thanks!

**Comment by yxsamliu** [comment]
Do we have a bi-way translation test for this?

**Comment by AlexeySotkin** [comment]
If you mean LLVM->SPIRV->LLVM, no. OpName instructions should be removed from SPIRV module to reproduce the issue. AFAIK there is no way to produce SPIRV without OpName with llvm-spirv tool. So I used manually stripped SPIRV module.

**Comment by yxsamliu** [comment]
This change affect function declaration name since it uses linkage name to overwrite the name of the function. Do we have test for the linkage name, otherwise how do we make sure the round-trip translated llvm IR still has correct function name?

**Comment by AlexeySotkin** [comment]
Many tests from test/SPIRV/transcoding directory check function names after round trip translation. For example spirv-types.ll, cl-types.ll, global_block.ll.

**Pull request merged**
